/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出全部職缺
         * @description 排序為最後出現時間由新到舊；篩選與排序由前端處理。
         */
        get: operations["get_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出可以選的縣市
         * @description 104 的 22 個縣市，依縣市選單的順序；不選代表全台灣。
         */
        get: operations["get_areas_api_crawl_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得抓取的狀態
         * @description 抓取中的進度、沒存入的抓取結果，或最近一次抓取沒有結果的原因。
         */
        get: operations["get_state_api_crawl_get"];
        put?: never;
        /**
         * 開始抓取
         * @description 在背景開始抓取，進度以 GET /api/crawl 取得。已有作業在跑，或有沒存入的抓取結果但沒有確認捨棄時回 409；開始時才捨棄舊的結果。
         */
        post: operations["start_crawl_api_crawl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止抓取
         * @description 不再發出新的請求，已送出的請求照常完成；取完內容的職缺進入預覽。
         */
        post: operations["stop_crawl_api_crawl_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 存入抓取結果
         * @description 把預覽的職缺整批寫入職缺資料庫，執行時間是抓完或停止的時間。成功時清掉預覽；寫入失敗時回 500，資料庫與預覽都不變。
         */
        post: operations["save_preview_api_crawl_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 捨棄抓取結果
         * @description 清掉沒存入的抓取結果，職缺資料庫不變。
         */
        delete: operations["discard_preview_api_crawl_preview_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得三份設定
         * @description 偏好、經歷、提示詞模板各自的版本紀錄（由新到舊）、目前設定是哪一版，以及預設內容。
         */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 檢查設定的內容
         * @description 編輯時即時檢查：偏好依欄位字典驗證；提示詞模板檢查標記與變數，沒用到的變數只提醒；經歷不檢查。
         */
        post: operations["check_content_api_settings_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{kind}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 儲存並套用新版本
         * @description 把內容存成新版本並改成目前設定；只要送來就新增，即使內容和其他版本相同。名稱空白或內容檢查有錯時回 422，什麼都不存。
         */
        post: operations["save_version_api_settings__kind__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{kind}/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 套用某一版
         * @description 把某一版改成目前設定，不新增版本。沒有這一版時回 404；內容檢查有錯時回 422。
         */
        put: operations["apply_api_settings__kind__current_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{kind}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改版本的名稱與描述
         * @description 只改名稱與描述，內容不能改。名稱空白時回 422；沒有這一版時回 404。
         */
        patch: operations["update_meta_api_settings__kind__versions__version__patch"];
        trace?: never;
    };
    "/api/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出各職缺代表的評分
         * @description 每筆評過分的職缺只列一筆：評分時間最新的一筆，同一秒內後寫入的；職缺表的評分欄位、排序與篩選都用它。
         */
        get: operations["get_scores_api_scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scores/{job_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取出一筆職缺的所有評分紀錄
         * @description 展開列用：每筆含評分明細與評分依據，依據中的提示詞由送評時的職缺快照與當時的設定版本組回。
         */
        get: operations["get_score_history_api_scores__job_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 送去評分前的確認
         * @description 確認視窗用：將評幾筆、其中幾筆淘汰、用哪一版設定，以及開始前的錯誤。
         */
        post: operations["plan_scoring_api_scoring_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得評分作業的狀態
         * @description 評分中的進度與每筆的狀態、最近一次結束的評分，以及正在跑的其他作業。
         */
        get: operations["get_scoring_state_api_scoring_get"];
        put?: never;
        /**
         * 開始評分
         * @description 重讀目前設定並重做開始前的檢查，有錯時回 422（detail 是錯誤清單）；已有作業在跑時回 409。通過後在背景照 codes 的順序逐筆評，進度以 GET /api/scoring 取得。
         */
        post: operations["start_scoring_api_scoring_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止評分
         * @description 評完目前這一筆就不再評，還在排隊的不評；已評完的留在資料庫。
         */
        post: operations["stop_scoring_api_scoring_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dry-run/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 試跑前的確認
         * @description 確認視窗用：將試跑幾筆、其中幾筆淘汰、用編輯區的什麼內容，以及開始前的錯誤。
         */
        post: operations["plan_dry_run_api_dry_run_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得試跑的狀態
         * @description 試跑中的進度與每筆的結果、最近一次結束的試跑，以及正在跑的其他作業。
         */
        get: operations["get_dry_run_state_api_dry_run_get"];
        put?: never;
        /**
         * 開始試跑
         * @description 重做開始前的檢查，有錯時回 422（detail 是錯誤清單）；已有作業在跑時回 409。通過後在背景照 codes 的順序逐筆評，不寫入評分紀錄；進度與結果以 GET /api/dry-run 取得。
         */
        post: operations["start_dry_run_api_dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dry-run/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止試跑
         * @description 評完目前這一筆就不再評，還在排隊的標成沒試跑。
         */
        post: operations["stop_dry_run_api_dry_run_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyVersion */
        ApplyVersion: {
            /** Version */
            version: number;
        };
        /** AreaList */
        AreaList: {
            /** Areas */
            areas: string[];
        };
        /** Basis */
        Basis: {
            preferences: components["schemas"]["VersionOut"];
            experience: components["schemas"]["VersionOut"];
            template: components["schemas"]["VersionOut"];
            /**
             * Snapshot
             * @description 送評時的職缺內容快照
             */
            snapshot: {
                [key: string]: string | number | null;
            };
            /** @description 由快照與三份設定的版本組回的提示詞；被淘汰或組不回來時為 null */
            prompt: components["schemas"]["PromptOut"] | null;
            /**
             * Prompt Error
             * @description 沒被淘汰卻組不回提示詞的原因
             */
            prompt_error: string | null;
        };
        /** CheckRequest */
        CheckRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "preferences" | "experience" | "template";
            /** Content */
            content: string;
        };
        /** CheckResult */
        CheckResult: {
            /**
             * Errors
             * @description 有錯誤時不能儲存或套用
             */
            errors: string[];
            /**
             * Warnings
             * @description 提醒，不擋儲存
             */
            warnings: string[];
        };
        /** CrawlRequest */
        CrawlRequest: {
            /**
             * Keyword
             * @description 多個關鍵字以半形或全形逗號分隔
             */
            keyword: string;
            /**
             * Area
             * @description 縣市名稱；null 代表全台灣
             */
            area?: string | null;
            /**
             * Pages
             * @description 每個關鍵字抓幾頁，每頁 30 筆
             */
            pages: number;
            /**
             * Job Type
             * @description 職缺性質：0 全部、1 全職、2 兼職／工讀
             * @enum {integer}
             */
            job_type: 0 | 1 | 2;
            /**
             * Discard Preview
             * @description 有沒存入的抓取結果時，確認捨棄它
             * @default false
             */
            discard_preview: boolean;
        };
        /** CrawlState */
        CrawlState: {
            /** @description 沒在抓取時為 null */
            running: components["schemas"]["Running"] | null;
            /** @description 沒有沒存入的抓取結果時為 null */
            preview: components["schemas"]["PreviewOut"] | null;
            /**
             * Outcome
             * @description 沒有預覽時，最近一次抓取的結果訊息
             */
            outcome: string | null;
        };
        /** CurrentScore */
        CurrentScore: {
            /** 職缺代碼 */
            "\u8077\u7F3A\u4EE3\u78BC": string;
            /** 評分時間 */
            "\u8A55\u5206\u6642\u9593": string;
            /** 淘汰 */
            "\u6DD8\u6C70": boolean;
            /** 總分 */
            "\u7E3D\u5206": number | null;
            /** 評語 */
            "\u8A55\u8A9E": string;
            /** 供應商 */
            "\u4F9B\u61C9\u5546": string | null;
            /** 模型 */
            "\u6A21\u578B": string | null;
            /**
             * 維度分數
             * @description 維度名稱 → 1–5 分或 null；被淘汰時為 null
             */
            "\u7DAD\u5EA6\u5206\u6578": {
                [key: string]: number | null;
            } | null;
        };
        /** DetailProgressOut */
        DetailProgressOut: {
            /**
             * Stage
             * @default detail
             * @constant
             */
            stage: "detail";
            /** Index */
            index: number;
            /** Total */
            total: number;
        };
        /** DimensionOut */
        DimensionOut: {
            /** 分數 */
            "\u5206\u6578": number | null;
            /** 理由 */
            "\u7406\u7531": string;
        };
        /** DraftIn */
        DraftIn: {
            /**
             * Base
             * @description 編輯區以哪一版為底
             */
            base: number;
            /**
             * Content
             * @description 編輯區目前的內容
             */
            content: string;
        };
        /** DraftOut */
        DraftOut: {
            /** Base */
            base: number;
            /**
             * Name
             * @description base 那一版的名稱
             */
            name: string;
            /**
             * Modified
             * @description 編輯區的內容和 base 那一版不同
             */
            modified: boolean;
            /**
             * Content
             * @description 試跑用的內容；和編輯區比較，就知道試跑後改過沒有
             */
            content: string;
        };
        /** DraftRef */
        DraftRef: {
            /** Base */
            base: number;
            /**
             * Name
             * @description base 那一版的名稱
             */
            name: string;
            /**
             * Modified
             * @description 編輯區的內容和 base 那一版不同
             */
            modified: boolean;
        };
        /** DraftsIn */
        DraftsIn: {
            preferences: components["schemas"]["DraftIn"];
            experience: components["schemas"]["DraftIn"];
            template: components["schemas"]["DraftIn"];
        };
        /** DryRunOut */
        DryRunOut: {
            /** Id */
            id: number;
            /** Total */
            total: number;
            /**
             * Done
             * @description 評完幾筆，含失敗
             */
            done: number;
            /** Model */
            model: string;
            /**
             * Settings
             * @description preferences、experience、template 各用了什麼內容
             */
            settings: {
                [key: string]: components["schemas"]["DraftOut"];
            };
            /** Stopping */
            stopping: boolean;
            /**
             * Stopped
             * @description 按了停止，或因為錯誤而停止
             */
            stopped: boolean;
            /**
             * Error
             * @description 讓試跑停止的錯誤
             */
            error: string | null;
            /**
             * Rows
             * @description 依試跑的順序
             */
            rows: components["schemas"]["DryRunRow"][];
        };
        /** DryRunPlan */
        DryRunPlan: {
            /**
             * Count
             * @description 將試跑幾筆
             */
            count: number;
            /**
             * Eliminated
             * @description 其中幾筆符合淘汰條件；偏好有錯時為 null
             */
            eliminated: number | null;
            /**
             * Settings
             * @description preferences、experience、template 各用編輯區的什麼內容
             */
            settings: {
                [key: string]: components["schemas"]["DraftRef"];
            };
            /** Provider */
            provider: string;
            /**
             * Models
             * @description 可以選的模型，第一個是預設
             */
            models: string[];
            /**
             * Errors
             * @description 開始前的錯誤；有錯誤時不能開始
             */
            errors: string[];
        };
        /** DryRunPlanRequest */
        DryRunPlanRequest: {
            /**
             * Codes
             * @description 試跑清單的職缺代碼，依清單的顯示順序
             */
            codes: string[];
            /** @description 三份設定編輯區的內容 */
            settings: components["schemas"]["DraftsIn"];
        };
        /** DryRunRow */
        DryRunRow: {
            /** Code */
            code: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "scoring" | "done" | "failed" | "skipped";
            /**
             * Reason
             * @description 試跑失敗的原因
             */
            reason: string | null;
            /** @description 試跑的評分結果；還沒評完或失敗時為 null */
            result: components["schemas"]["ScoreDetails"] | null;
        };
        /** DryRunStartRequest */
        DryRunStartRequest: {
            /**
             * Codes
             * @description 試跑清單的職缺代碼，依清單的顯示順序
             */
            codes: string[];
            /** @description 三份設定編輯區的內容 */
            settings: components["schemas"]["DraftsIn"];
            /** Model */
            model: string;
        };
        /** DryRunStarted */
        DryRunStarted: {
            /** Run Id */
            run_id: number;
        };
        /** DryRunState */
        DryRunState: {
            /** @description 沒在試跑時為 null */
            running: components["schemas"]["DryRunOut"] | null;
            /** @description 最近一次結束的試跑；web app 啟動後還沒試跑過時為 null */
            last: components["schemas"]["DryRunOut"] | null;
            /**
             * Busy
             * @description 正在跑的其他作業，例如「評分」
             */
            busy: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** 職缺代碼 */
            "\u8077\u7F3A\u4EE3\u78BC": string;
            /** 職缺名稱 */
            "\u8077\u7F3A\u540D\u7A31": string | null;
            /** 公司名稱 */
            "\u516C\u53F8\u540D\u7A31": string | null;
            /** 產業類別 */
            "\u7522\u696D\u985E\u5225": string | null;
            /** 地區 */
            "\u5730\u5340": string | null;
            /** 薪資待遇 */
            "\u85AA\u8CC7\u5F85\u9047": string | null;
            /** 薪資下限 */
            "\u85AA\u8CC7\u4E0B\u9650": number | null;
            /** 薪資上限 */
            "\u85AA\u8CC7\u4E0A\u9650": number | null;
            /** 更新日期 */
            "\u66F4\u65B0\u65E5\u671F": string | null;
            /** 應徵人數 */
            "\u61C9\u5FB5\u4EBA\u6578": number | null;
            /** 工作內容 */
            "\u5DE5\u4F5C\u5167\u5BB9": string | null;
            /** 電腦專長 */
            "\u96FB\u8166\u5C08\u9577": string | null;
            /** 科系要求 */
            "\u79D1\u7CFB\u8981\u6C42": string | null;
            /** 特色標籤 */
            "\u7279\u8272\u6A19\u7C64": string | null;
            /** 職缺連結 */
            "\u8077\u7F3A\u9023\u7D50": string | null;
            /** 公司連結 */
            "\u516C\u53F8\u9023\u7D50": string | null;
            /** 首次出現時間 */
            "\u9996\u6B21\u51FA\u73FE\u6642\u9593": string;
            /** 最後出現時間 */
            "\u6700\u5F8C\u51FA\u73FE\u6642\u9593": string;
        };
        /** JobFields */
        JobFields: {
            /** 職缺代碼 */
            "\u8077\u7F3A\u4EE3\u78BC": string;
            /** 職缺名稱 */
            "\u8077\u7F3A\u540D\u7A31": string | null;
            /** 公司名稱 */
            "\u516C\u53F8\u540D\u7A31": string | null;
            /** 產業類別 */
            "\u7522\u696D\u985E\u5225": string | null;
            /** 地區 */
            "\u5730\u5340": string | null;
            /** 薪資待遇 */
            "\u85AA\u8CC7\u5F85\u9047": string | null;
            /** 薪資下限 */
            "\u85AA\u8CC7\u4E0B\u9650": number | null;
            /** 薪資上限 */
            "\u85AA\u8CC7\u4E0A\u9650": number | null;
            /** 更新日期 */
            "\u66F4\u65B0\u65E5\u671F": string | null;
            /** 應徵人數 */
            "\u61C9\u5FB5\u4EBA\u6578": number | null;
            /** 工作內容 */
            "\u5DE5\u4F5C\u5167\u5BB9": string | null;
            /** 電腦專長 */
            "\u96FB\u8166\u5C08\u9577": string | null;
            /** 科系要求 */
            "\u79D1\u7CFB\u8981\u6C42": string | null;
            /** 特色標籤 */
            "\u7279\u8272\u6A19\u7C64": string | null;
            /** 職缺連結 */
            "\u8077\u7F3A\u9023\u7D50": string | null;
            /** 公司連結 */
            "\u516C\u53F8\u9023\u7D50": string | null;
        };
        /** JobList */
        JobList: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** KindState */
        KindState: {
            /**
             * Current
             * @description 目前設定是第幾版
             */
            current: number;
            /**
             * Is Default
             * @description 目前設定的內容是否和專案附的預設內容相同
             */
            is_default: boolean;
            /**
             * Default Content
             * @description 專案附的預設內容，「還原預設」用
             */
            default_content: string;
            /**
             * Versions
             * @description 由新到舊
             */
            versions: components["schemas"]["Version"][];
        };
        /** NewVersion */
        NewVersion: {
            /**
             * Name
             * @description 必填，頭尾的空白會去掉
             */
            name: string;
            /**
             * Description
             * @description 可以空白
             * @default
             */
            description: string;
            /** Content */
            content: string;
        };
        /** Plan */
        Plan: {
            /**
             * Selected
             * @description 勾選幾筆
             */
            selected: number;
            /**
             * Scored
             * @description 勾選的職缺中幾筆已評過
             */
            scored: number;
            /**
             * Targets
             * @description 將評幾筆
             */
            targets: number;
            /**
             * Eliminated
             * @description 將評的職缺中幾筆符合淘汰條件；偏好有錯時為 null
             */
            eliminated: number | null;
            /**
             * Versions
             * @description 目前設定：preferences、experience、template
             */
            versions: {
                [key: string]: components["schemas"]["VersionRef"];
            };
            /** Provider */
            provider: string;
            /**
             * Models
             * @description 可以選的模型，第一個是預設
             */
            models: string[];
            /**
             * Errors
             * @description 開始前的錯誤；有錯誤時不能送出
             */
            errors: string[];
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Codes
             * @description 勾選的職缺代碼，依職缺表的顯示順序
             */
            codes: string[];
            /**
             * Rescore
             * @description 包含已評過的職缺（重評）
             */
            rescore: boolean;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Jobs */
            jobs: components["schemas"]["JobFields"][];
            /**
             * New Codes
             * @description 職缺資料庫裡還沒有的職缺代碼
             */
            new_codes: string[];
            /** Found */
            found: number;
            /** Stopped */
            stopped: boolean;
        };
        /** PromptOut */
        PromptOut: {
            /** System */
            system: string;
            /** User */
            user: string;
        };
        /** RowStatus */
        RowStatus: {
            /** Code */
            code: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "scoring" | "failed";
            /**
             * Reason
             * @description 評分失敗的原因
             */
            reason: string | null;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: number;
            /** Total */
            total: number;
            /**
             * Done
             * @description 評完幾筆，含失敗
             */
            done: number;
            /**
             * Ok
             * @description 評分成功、沒被淘汰
             */
            ok: number;
            /** Eliminated */
            eliminated: number;
            /** Failed */
            failed: number;
            /**
             * Skipped
             * @description 停止後沒評的筆數
             */
            skipped: number;
            /** Stopping */
            stopping: boolean;
            /**
             * Stopped
             * @description 按了停止，或因為錯誤而停止
             */
            stopped: boolean;
            /**
             * Error
             * @description 讓評分停止的錯誤
             */
            error: string | null;
            /**
             * Statuses
             * @description 還沒評完或評分失敗的職缺，依評分的順序
             */
            statuses: components["schemas"]["RowStatus"][];
        };
        /** Running */
        Running: {
            /**
             * Progress
             * @description 還沒送出第一個請求時為 null
             */
            progress: components["schemas"]["SearchProgressOut"] | components["schemas"]["DetailProgressOut"] | null;
            /** Stopping */
            stopping: boolean;
        };
        /** SavedCodes */
        SavedCodes: {
            /**
             * Codes
             * @description 這次存入的職缺代碼，順序同預覽
             */
            codes: string[];
        };
        /** SavedVersion */
        SavedVersion: {
            /**
             * Version
             * @description 新版本的編號，已經改成目前設定
             */
            version: number;
        };
        /** ScoreDetails */
        ScoreDetails: {
            /** 職缺代碼 */
            "\u8077\u7F3A\u4EE3\u78BC": string;
            /** 淘汰 */
            "\u6DD8\u6C70": boolean;
            /** 淘汰原因 */
            "\u6DD8\u6C70\u539F\u56E0": string[];
            /**
             * 維度
             * @description 依維度的順序排列；被淘汰時為 null
             */
            "\u7DAD\u5EA6": {
                [key: string]: components["schemas"]["DimensionOut"];
            } | null;
            /** 總分 */
            "\u7E3D\u5206": number | null;
            /** 未知維度 */
            "\u672A\u77E5\u7DAD\u5EA6": string[];
            /** 評語 */
            "\u8A55\u8A9E": string;
        };
        /** ScoreHistory */
        ScoreHistory: {
            /**
             * Records
             * @description 依評分時間由新到舊，同一秒內後寫入的在前；沒評過時為空清單
             */
            records: components["schemas"]["ScoreRecord"][];
        };
        /** ScoreList */
        ScoreList: {
            /**
             * Scores
             * @description 每筆評過分的職缺一筆代表的評分；沒評過的職缺不在其中
             */
            scores: components["schemas"]["CurrentScore"][];
        };
        /** ScoreRecord */
        ScoreRecord: {
            /** 評分時間 */
            "\u8A55\u5206\u6642\u9593": string;
            /** 淘汰 */
            "\u6DD8\u6C70": boolean;
            /** 總分 */
            "\u7E3D\u5206": number | null;
            /** 評語 */
            "\u8A55\u8A9E": string;
            /** 供應商 */
            "\u4F9B\u61C9\u5546": string | null;
            /** 模型 */
            "\u6A21\u578B": string | null;
            "\u8A55\u5206\u660E\u7D30": components["schemas"]["ScoreDetails"];
            /** @description 評分依據；記錄依據之前的評分為 null */
            basis: components["schemas"]["Basis"] | null;
        };
        /** ScoringState */
        ScoringState: {
            /** @description 沒在評分時為 null */
            running: components["schemas"]["RunOut"] | null;
            /** @description 最近一次結束的評分；web app 啟動後還沒評過時為 null */
            last: components["schemas"]["RunOut"] | null;
            /**
             * Busy
             * @description 正在跑的其他作業，例如「抓取」
             */
            busy: string | null;
        };
        /** SearchProgressOut */
        SearchProgressOut: {
            /**
             * Stage
             * @default search
             * @constant
             */
            stage: "search";
            /** Keyword */
            keyword: string;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
            /** Found */
            found: number;
        };
        /** SettingsState */
        SettingsState: {
            preferences: components["schemas"]["KindState"];
            experience: components["schemas"]["KindState"];
            template: components["schemas"]["KindState"];
        };
        /** StartRequest */
        StartRequest: {
            /**
             * Codes
             * @description 勾選的職缺代碼，依職缺表的顯示順序
             */
            codes: string[];
            /**
             * Rescore
             * @description 包含已評過的職缺（重評）
             */
            rescore: boolean;
            /** Model */
            model: string;
        };
        /** Started */
        Started: {
            /** Run Id */
            run_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Version */
        Version: {
            /** Version */
            version: number;
            /** Name */
            name: string;
            /**
             * Description
             * @description 沒有填時是空字串
             */
            description: string;
            /**
             * Saved At
             * @description 儲存時間，本地時間 ISO 8601，精確到秒
             */
            saved_at: string;
            /** Content */
            content: string;
        };
        /** VersionMeta */
        VersionMeta: {
            /**
             * Name
             * @description 必填，頭尾的空白會去掉
             */
            name: string;
            /**
             * Description
             * @description 可以空白
             * @default
             */
            description: string;
        };
        /** VersionOut */
        VersionOut: {
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Saved At */
            saved_at: string;
            /** Content */
            content: string;
        };
        /** VersionRef */
        VersionRef: {
            /** Version */
            version: number;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
        };
    };
    get_areas_api_crawl_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaList"];
                };
            };
        };
    };
    get_state_api_crawl_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlState"];
                };
            };
        };
    };
    start_crawl_api_crawl_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_crawl_api_crawl_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_preview_api_crawl_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedCodes"];
                };
            };
        };
    };
    discard_preview_api_crawl_preview_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsState"];
                };
            };
        };
    };
    check_content_api_settings_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_version_api_settings__kind__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "preferences" | "experience" | "template";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewVersion"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_api_settings__kind__current_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "preferences" | "experience" | "template";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyVersion"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meta_api_settings__kind__versions__version__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "preferences" | "experience" | "template";
                version: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionMeta"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scores_api_scores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreList"];
                };
            };
        };
    };
    get_score_history_api_scores__job_no__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_no: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_scoring_api_scoring_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoring_state_api_scoring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringState"];
                };
            };
        };
    };
    start_scoring_api_scoring_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Started"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_scoring_api_scoring_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    plan_dry_run_api_dry_run_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DryRunPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dry_run_state_api_dry_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunState"];
                };
            };
        };
    };
    start_dry_run_api_dry_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DryRunStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_dry_run_api_dry_run_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
